export const GEO_DATA = [
  /* ===================== Vietnam (84) ===================== */
  { id: '84000', title: 'Vietnam', name: 'Vietnam' },
  { id: '84001', title: 'Ha Noi, Vietnam', name: 'Ha Noi' },
  { id: '84002', title: 'Ho Chi Minh City, Vietnam', name: 'Ho Chi Minh' },
  { id: '84003', title: 'Da Nang, Vietnam', name: 'Da Nang' },
  { id: '84004', title: 'Hai Phong, Vietnam', name: 'Hai Phong' },
  { id: '84005', title: 'Can Tho, Vietnam', name: 'Can Tho' },
  { id: '84006', title: 'Hue, Vietnam', name: 'Hue' },
  { id: '84007', title: 'Nha Trang, Vietnam', name: 'Nha Trang' },
  { id: '84008', title: 'Vung Tau, Vietnam', name: 'Vung Tau' },
  { id: '84009', title: 'Da Lat, Vietnam', name: 'Da Lat' },
  { id: '84010', title: 'Quy Nhon, Vietnam', name: 'Quy Nhon' },
  { id: '84011', title: 'Bien Hoa, Vietnam', name: 'Bien Hoa' },
  { id: '84012', title: 'Buon Ma Thuot, Vietnam', name: 'Buon Ma Thuot' },
  { id: '84013', title: 'Phan Thiet, Vietnam', name: 'Phan Thiet' },
  { id: '84014', title: 'Long Xuyen, Vietnam', name: 'Long Xuyen' },
  { id: '84015', title: 'Rach Gia, Vietnam', name: 'Rach Gia' },

  /* ===================== France (33) ===================== */
  { id: '33000', title: 'France', name: 'France' },
  { id: '33001', title: 'Paris, France', name: 'Paris' },
  { id: '33002', title: 'Marseille, France', name: 'Marseille' },
  { id: '33003', title: 'Lyon, France', name: 'Lyon' },
  { id: '33004', title: 'Toulouse, France', name: 'Toulouse' },
  { id: '33005', title: 'Nice, France', name: 'Nice' },
  { id: '33006', title: 'Nantes, France', name: 'Nantes' },
  { id: '33007', title: 'Strasbourg, France', name: 'Strasbourg' },
  { id: '33008', title: 'Montpellier, France', name: 'Montpellier' },
  { id: '33009', title: 'Bordeaux, France', name: 'Bordeaux' },
  { id: '33010', title: 'Lille, France', name: 'Lille' },
  { id: '33011', title: 'Rennes, France', name: 'Rennes' },
  { id: '33012', title: 'Reims, France', name: 'Reims' },
  { id: '33013', title: 'Le Havre, France', name: 'Le Havre' },
  { id: '33014', title: 'Cannes, France', name: 'Cannes' },

  /* ===================== China (86) ===================== */
  { id: '86000', title: 'China', name: 'China' },
  { id: '86001', title: 'Beijing, China', name: 'Beijing' },
  { id: '86002', title: 'Shanghai, China', name: 'Shanghai' },
  { id: '86003', title: 'Guangzhou, China', name: 'Guangzhou' },
  { id: '86004', title: 'Shenzhen, China', name: 'Shenzhen' },
  { id: '86005', title: 'Chengdu, China', name: 'Chengdu' },
  { id: '86006', title: 'Wuhan, China', name: 'Wuhan' },
  { id: '86008', title: 'Hangzhou, China', name: 'Hangzhou' },
  { id: '86009', title: 'Nanjing, China', name: 'Nanjing' },
  { id: '86010', title: 'Suzhou, China', name: 'Suzhou' },
  { id: '86011', title: 'Tianjin, China', name: 'Tianjin' },
  { id: '86012', title: 'Chongqing, China', name: 'Chongqing' },
  { id: '86013', title: 'Qingdao, China', name: 'Qingdao' },
  { id: '86014', title: 'Dalian, China', name: 'Dalian' },

  /* ===================== USA (1) ===================== */
  { id: '1000', title: 'United States', name: 'United States' },
  { id: '1001', title: 'New York, USA', name: 'New York' },
  { id: '1002', title: 'Los Angeles, USA', name: 'Los Angeles' },
  { id: '1003', title: 'Chicago, USA', name: 'Chicago' },
  { id: '1004', title: 'Houston, USA', name: 'Houston' },
  { id: '1005', title: 'Phoenix, USA', name: 'Phoenix' },
  { id: '1006', title: 'San Diego, USA', name: 'San Diego' },
  { id: '1007', title: 'Dallas, USA', name: 'Dallas' },
  { id: '1008', title: 'San Jose, USA', name: 'San Jose' },
  { id: '1009', title: 'Austin, USA', name: 'Austin' },
  { id: '1010', title: 'Seattle, USA', name: 'Seattle' },
  { id: '1011', title: 'San Francisco, USA', name: 'San Francisco' },
  { id: '1012', title: 'Boston, USA', name: 'Boston' },
  { id: '1013', title: 'Miami, USA', name: 'Miami' },
  { id: '1014', title: 'Atlanta, USA', name: 'Atlanta' },

  /* ===================== Korea (82) ===================== */
  { id: '82000', title: 'South Korea', name: 'South Korea' },
  { id: '82001', title: 'Seoul, South Korea', name: 'Seoul' },
  { id: '82002', title: 'Busan, South Korea', name: 'Busan' },
  { id: '82003', title: 'Incheon, South Korea', name: 'Incheon' },
  { id: '82004', title: 'Daegu, South Korea', name: 'Daegu' },
  { id: '82005', title: 'Daejeon, South Korea', name: 'Daejeon' },
  { id: '82006', title: 'Gwangju, South Korea', name: 'Gwangju' },
  { id: '82007', title: 'Suwon, South Korea', name: 'Suwon' },
  { id: '82008', title: 'Ulsan, South Korea', name: 'Ulsan' },
  { id: '82009', title: 'Changwon, South Korea', name: 'Changwon' },
  { id: '82010', title: 'Seongnam, South Korea', name: 'Seongnam' },
  { id: '82011', title: 'Yongin, South Korea', name: 'Yongin' },
  { id: '82012', title: 'Goyang, South Korea', name: 'Goyang' },
  { id: '82013', title: 'Jeonju, South Korea', name: 'Jeonju' },
  { id: '82014', title: 'Cheongju, South Korea', name: 'Cheongju' },

  /* ===================== Japan (81) ===================== */
  { id: '81000', title: 'Japan', name: 'Japan' },
  { id: '81001', title: 'Tokyo, Japan', name: 'Tokyo' },
  { id: '81002', title: 'Osaka, Japan', name: 'Osaka' },
  { id: '81003', title: 'Kyoto, Japan', name: 'Kyoto' },
  { id: '81004', title: 'Yokohama, Japan', name: 'Yokohama' },
  { id: '81005', title: 'Nagoya, Japan', name: 'Nagoya' },
  { id: '81006', title: 'Sapporo, Japan', name: 'Sapporo' },
  { id: '81007', title: 'Fukuoka, Japan', name: 'Fukuoka' },
  { id: '81008', title: 'Kobe, Japan', name: 'Kobe' },
  { id: '81009', title: 'Hiroshima, Japan', name: 'Hiroshima' },
  { id: '81010', title: 'Sendai, Japan', name: 'Sendai' },
  { id: '81011', title: 'Chiba, Japan', name: 'Chiba' },
  { id: '81012', title: 'Kawasaki, Japan', name: 'Kawasaki' },
  { id: '81013', title: 'Saitama, Japan', name: 'Saitama' },
  { id: '81014', title: 'Naha, Japan', name: 'Naha' },
];
